name: Approve

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main


jobs:
  approve_dependabot_pr:
    runs-on: ubuntu-latest
    name: Auto-approve Boto3 Pull Request
    if: github.actor == 'kojiromike' && startsWith(github.head_ref, 'approv')
    steps:
    - name: Setup GH
      run: gh auth login --with-token <<< '${{ secrets.GITHUB_TOKEN }}'
    - name: Approve Pull Request
      run: gh pr review '${{ github.event.pull_request._links.html.href }}' --approve --body 'Automatically approved by GitHub action workflow ${{ github.workflow }} run ${{ github.run_number }}'
    - name: Enable Auto-Merge
      run: |
        gh pr merge '${{ github.event.pull_request._links.html.href }}' --squash --auto ||
        gh pr merge '${{ github.event.pull_request._links.html.href }}' --squash
