name: Release

on:
  workflow_dispatch:
  release:
    created:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - run: echo 'created release'

    # - uses: actions/checkout@v2

    # - name: Setup Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python }}
